### ISSUE TITLE
Styling problems in Login-page 

### ISSUE THREAD

**Issue by BennyPerumalla** [lugnitdgp/GSoC_Slack-Clone#10]
![Screenshot 2024-10-13 173027](https://github.com/user-attachments/assets/f8309584-7d5a-4d0c-a5e9-4de8ce3dec8d)

@Pudi-Sravan I would like to optimize the styling for the login-page and to add feature to make the button more attractive

**Comment by Pudi-Sravan** [comment]
Sure i will assign you this and send a screenshot of the changes you made after you are done

**Comment by BennyPerumalla** [comment]
![Screenshot 2024-10-14 172413](https://github.com/user-attachments/assets/175306d0-248e-4e2e-a334-fc395ffeb00e)
![Screenshot 2024-10-14 172429](https://github.com/user-attachments/assets/d03a3484-e318-4654-8ff5-b650903be19e)
![Screenshot 2024-10-14 175113](https://github.com/user-attachments/assets/4e464530-fcb2-4b41-8f8a-a9c069c32131)
![Screenshot 2024-10-14 175122](https://github.com/user-attachments/assets/05b96449-e48e-4b0e-b928-f3ae2efb4081)
These are the changes I made, Can I make a PR? @Pudi-Sravan

**Comment by BennyPerumalla** [comment]
Here are the changes I made, Can I submit my PR @Pudi-Sravan 
![Screenshot 2024-10-14 213844](https://github.com/user-attachments/assets/f37b932c-24c2-4648-b530-3f1d3bb91896)
![Screenshot 2024-10-14 213855](https://github.com/user-attachments/assets/45a6b90a-d9bf-4be3-9486-fc99105c4006)
![Screenshot 2024-10-14 213915](https://github.com/user-attachments/assets/6e31b3be-f5de-4b1f-9f1f-68e1bf9b07d4)

**Comment by Pudi-Sravan** [comment]
Cool @BennyPerumalla could you change the background colour of the Log in button to a bit of orange instead of yellow so it matches the theme.
